### ISSUE TITLE
Add Support for input files

### ISSUE THREAD

**Issue by olaelkhatib** [ObeidaElJundi/Correctomation#4]
If the input is a file:

1. Add a check box for "Hardcoded Filename input"
2. If the file option is checked,  the the input.txt file contains the path to the different files (testcases).
3. Change the following in the _temp.cpp file that was created before running it:
- Get the _propertyname_ by searching for  ifstream _propertyname_
- Search for _propertyname_ .open(**filename**) 
- Replace the filename by that listed in the input.txt

**Comment by olaelkhatib** [comment]
Note that the file could be created as follows: ifstream iData(filename); So we need to take this into consideration as well.

**Comment by olaelkhatib** [comment]
An exception is thrown: 
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\oe17\Desktop\Prob2' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

**Comment by olaelkhatib** [comment]
Comments: 
1. The path to input and output files better be relative. The code will parse the path from the input and output fields.
2. The input file names (inData_1.txt, inData_2.txt...) should be read from the file input.txt and replaced in the {cpp_file}_temp.cpp

**Comment by olaelkhatib** [comment]
Done. Some bugs were inserted in separate issues.
